#! /usr/bin/env perl

use strict;
use FindBin;
use POSIX;
use Math::Complex;

require $FindBin::RealBin . "/ceqAnalyzeCommon.pm";

my @argument = ParseArgument(\@ARGV);


if ($#argument != 1) {
	my $cmd = `basename $0`;
	chomp $cmd;
	print "usage: $cmd coef_as_b1 Fs\n";
	print " --+-|>-(+)----+--\n";
	print "   | a0 / \\    |  \n";
	print "   +-|>+   +<|-+  \n";
	print "     a1     b1    \n";
	exit 1;
}

my $coef = shift @argument;
my $Fs = shift @argument;

my $freq = $Fs / pi() * atan2((1-$coef), (1+$coef));

print "freq --> $freq\n\n";

## as LPF

my $coef_a = (1 - $coef) / 2;
my $coef_b = $coef_a;

my $coef_as = int(log(abs($coef_a))/log(2));
if ($coef_as < 0) { $coef_as = 0; }
if ($coef_as == 3) { $coef_as = 2; }
my $coef_bs = int(log(abs($coef_b))/log(2));
if ($coef_bs < 0) { $coef_bs = 0; }
if ($coef_bs == 3) { $coef_bs = 2; }

print "as LPF...\n";
printf "coef_a = %12.9f	%12.9f(<<%d)  (w/o shift)=0x%08x  (w/ shift)=0x%04x (<<%d)\n",
	$coef_a, $coef_a / 2**$coef_as, $coef_as, round($coef_a * 0x800000),
	0xffff & round($coef_a / 2**$coef_as * 0x8000), $coef_as;

printf "coef_b = %12.9f	%12.9f(<<%d)  (w/o shift)=0x%08x  (w/ shift)=0x%04x (<<%d)\n",
	$coef_b, $coef_b / 2**$coef_bs, $coef_bs, round($coef_b * 0x800000),
	0xffff & round($coef_b / 2**$coef_bs * 0x8000), $coef_bs;

## as HPF

my $coef_a = (1 + $coef) / 2;
my $coef_b = -$coef_a;

my $coef_as = int(log(abs($coef_a))/log(2));
if ($coef_as < 0) { $coef_as = 0; }
if ($coef_as == 3) { $coef_as = 2; }
my $coef_bs = int(log(abs($coef_b))/log(2));
if ($coef_bs < 0) { $coef_bs = 0; }
if ($coef_bs == 3) { $coef_bs = 2; }

print "as HPF...\n";
printf "coef_a = %12.9f	%12.9f(<<%d)  (w/o shift)=0x%08x  (w/ shift)=0x%04x (<<%d)\n",
	$coef_a, $coef_a / 2**$coef_as, $coef_as, round($coef_a * 0x800000),
	0xffff & round($coef_a / 2**$coef_as * 0x8000), $coef_as;

printf "coef_b = %12.9f	%12.9f(<<%d)  (w/o shift)=0x%08x  (w/ shift)=0x%04x (<<%d)\n",
	$coef_b, $coef_b / 2**$coef_bs, $coef_bs, round($coef_b * 0x800000),
	0xffff & round($coef_b / 2**$coef_bs * 0x8000), $coef_bs;
