#! /usr/bin/env perl

use strict;
use FindBin;
use POSIX;
use Math::Complex;

require $FindBin::RealBin . "/ceqAnalyzeCommon.pm";



my %argument_hash = ParseArgument(\@ARGV);

if ($#{ $argument_hash{ "argument" } } != 3) {
	my $cmd = `basename $0`;
	chomp $cmd;
	print "usage: $cmd a0 a1 b1 Fs\n";
	print " --+-|>-(+)----+--\n";
	print "   | a0 / \\    |  \n";
	print "   +-|>+   +<|-+  \n";
	print "     a1     b1    \n";
	exit 1;
}

my $option_arg;
foreach my $key (keys %{ $argument_hash{ "option" } }) {
	my $val = $argument_hash{ "option" }->{ $key };
	$option_arg .= " $key=$val";
}

my ($a0, $a1, $b1, $Fs) = @{ $argument_hash{ "argument" } };

system ($FindBin::RealBin . "/ceqEAanalyze $a0 $a1 0 $b1 0 $Fs $option_arg");
