#! /usr/bin/env perl

use strict;
use FindBin;
use POSIX;
use Math::Complex;

require $FindBin::RealBin . "/ceqAnalyzeCommon.pm";

my @argument = ParseArgument(\@ARGV);


if ($#argument != 3) {
	my $cmd = `basename $0`;
	chomp $cmd;
	print "usage: $cmd att a0 a1 Fs\n";
	print "           +-----------------|>---+\n";
	print "           |                (a1)  |\n";
	print "           |                      V\n";
	print " --|>--(+)---|>--(+)-----+---|>--(+)--\n";
	print "  att    \\   a0    \\     |  (a1)\n";
	print "          \\         \\   [ ] \n";
	print "           \\         \\   |  \n";
	print "            +---<|----+--+  \n";
	print "                -1\n";
	exit 1;
}

my ($att, $a0, $a1, $Fs) = @argument;


# HSV
my $a0_hsv = $att * $a1;
my $a1_hsv = $att * ($a0 - $a1);
my $b1_hsv = 1 - $a0;

# LSV
my $a0_lsv = $att;
my $a1_lsv = $att * ($a0 * $a1 - 1);
my $b1_lsv = 1 - $a0;

# HPF
my $a0_hpf = $att;
my $a1_hpf = -$att;
my $b1_hpf = 1 - $a0;

# LPF
my $a0_lpf = $att * $a0;
my $a1_lpf = 0;
my $b1_lpf = 1 - $a0;



print "as HSV ...\n";
system ($FindBin::RealBin . "/ceqFAanalyze $a0_hsv $a1_hsv $b1_hsv $Fs");
print "\n";

print "as LSV ...\n";
system ($FindBin::RealBin . "/ceqFAanalyze $a0_lsv $a1_lsv $b1_lsv $Fs");
print "\n";

print "as HPF ...\n";
system ($FindBin::RealBin . "/ceqFAanalyze $a0_hpf $a1_hpf $b1_hpf $Fs");
print "\n";

print "as LPF ...\n";
system ($FindBin::RealBin . "/ceqFAanalyze $a0_lpf $a1_lpf $b1_lpf $Fs");
