#! /usr/bin/env perl

sub usage {
	my ($cmd) = @_;
	print "dBu --> V(0-peak) converter\n";
	print "usage: $cmd dBu_value\n";
}

if ($#ARGV != 0) {
	my $cmd = `basename $0`;
	chomp $cmd;
	usage($cmd);
	exit 1;
}


$dBu = shift;

$val0dBu = sqrt(0.6);	# 0dBu = 0.775Vrms (= sqrt(0.6)

$v0pval = $val0dBu * 10 ** ($dBu / 20) * sqrt(2);

print "$v0pval\n";
