#! /usr/bin/env perl

use strict;
my $option;

sub usage {
	my $cmd = `basename $0`;
	chomp $cmd;
	print "-- wav to binary converter --\n";
	print "usage: $cmd [--convert-endian] inFile(*.wav) outFile(*.bin)\n";
	print "\n";
}

if ($ARGV[0] =~ /--(.+)/) {
	$option = $1;
	shift;
}

if ($#ARGV != 1) {
	usage();
	exit 1;
}

my $infile = shift;
my $outfile = shift;

open(IN, "$infile") or die "cannot open $infile!\n";
binmode IN;

my $buf;
read IN, $buf, 4;	# RIFF
read IN, $buf, 4;	# size
read IN, $buf, 4;	# WAVE
read IN, $buf, 4;	# fmt 
read IN, $buf, 4;	# size of fmt
my $size = unpack "V", $buf;
read IN, $buf, 2;	# type (PCM)
read IN, $buf, 2;	# num of channel
my $NUM_OF_CH = unpack "v", $buf;
read IN, $buf, 4;	# sample rate
read IN, $buf, 4;	# bit rate (= sample_rate * num_of_channel * bit_length / 8)
read IN, $buf, 2;	# block size (= bit_length / 8 * num_of_channel)
read IN, $buf, 2;	# bit_length
my $BIT_LENGTH = unpack "v", $buf;

if ($NUM_OF_CH == 1) {
	open(OUT, "> $outfile") or die "cannot open $outfile!\n";
	binmode OUT;
} elsif ($NUM_OF_CH == 2) {
	my $outfile_l = $outfile;
	$outfile_l =~ s/\.([^.]+)$/_l\.$1/;
	my $outfile_r = $outfile;
	$outfile_r =~ s/\.([^.]+)$/_r\.$1/;
	open(OUT_L, "> $outfile_l") or die "cannot open $outfile_l!\n";
	open(OUT_R, "> $outfile_r") or die "cannot open $outfile_r!\n";
	binmode OUT_L;
	binmode OUT_R;
}


read IN, $buf, ($size - 16);	# skip remaining fmt

read IN, $buf, 4;	# data
my $chunk = $buf;
while ($chunk ne "data") {
	print "skipping chunk $chunk...\n";
	read IN, $buf, 4;	# size of fmt
	my $size = unpack "V", $buf;
	read IN, $buf, $size;
	read IN, $buf, 4;
	$chunk = $buf;
}

read IN, $buf, 4;	# size of fmt
my $size = unpack "V", $buf;

while($size > 0) {
	if ($BIT_LENGTH == 16) {
		for (my $ch = 0; $ch < $NUM_OF_CH; $ch++) {
			my $buf;
			read IN, $buf, 2;	# wav body
			if ($option eq "convert-endian") {
				my $data = unpack "v", $buf;
				$buf = pack "n", ($data);
			}
			if ($NUM_OF_CH == 1) {
				print (OUT $buf);
			} elsif (($NUM_OF_CH == 2) && ($ch == 0)) {
				print (OUT_L $buf);
			} else {
				print (OUT_R $buf);
			}
		}
	} elsif ($BIT_LENGTH == 32) {
		for (my $ch = 0; $ch < $NUM_OF_CH; $ch++) {
			my $buf;
			read IN, $buf, 4;	# wav body
			if ($option eq "convert-endian") {
				my $data = unpack "V", $buf;
				$buf = pack "N", ($data);
			}
			if ($NUM_OF_CH == 1) {
				print (OUT $buf);
			} elsif (($NUM_OF_CH == 2) && ($ch == 0)) {
				print (OUT_L $buf);
			} else {
				print (OUT_R $buf);
			}
		}
	}
	$size -= $BIT_LENGTH / 8 * $NUM_OF_CH;
}

close(IN);
if ($NUM_OF_CH == 1) {
	close(OUT);
} else {
	close(OUT_L);
	close(OUT_R);
}
