#! /usr/bin/env perl

use strict;
use FindBin;

require $FindBin::RealBin . "/wav_util.pm";


sub usage {
	my $cmd = `basename $0`;
	chomp $cmd;
	print "-- wav to dat converter --\n";
	print "usage: $cmd inFile(*.wav) outFile(*.dat)\n";
	print "\n";
}

if ($#ARGV != 1) {
	usage();
	exit 1;
}



my @APF00;
my @APF01;

my @APF10;
my @APF11;

my @DCF0;
my @DCF1;

my $DCF00 =  0.999643937;		# DC Cut filter
my $DCF01 = -0.999643937;
my $DCF02 =  0.999287874;

sub Process {
	my ($data, $ch) = @_;

	{
	    my $r3 = $data * 0.33333 + 0.33334;
	    my $r7 = -$r3 * $r3 + 2.0;
	    my $r6 =  $r3 * $r3 + 2.0;
	    my $apfcoef = $r7 / $r6;

	    $APF01[$ch] = -$data * $apfcoef + $APF01[$ch] * $apfcoef + $APF00[$ch];
	    $APF00[$ch] = $data;

	    $data = $APF01[$ch];
	}

	{
	    my $r3 = $data * 0.33333 + 0.33334;
	    my $r7 = -$r3 * $r3 + 2.0;
	    my $r6 =  $r3 * $r3 + 2.0;
	    my $apfcoef = $r7 / $r6;

	    $APF11[$ch] = -$data * $apfcoef + $APF11[$ch] * $apfcoef + $APF10[$ch];
	    $APF10[$ch] = $data;

	    $data = $APF11[$ch];
	}

	return $data;

#	$DCF1[$ch] = $APF1[$ch] * $DCF00 + $DCF0[$ch] * $DCF01 + $DCF1[$ch] * $DCF02;
#	$DCF0[$ch] = $APF1[$ch];

#	printf("data: $data\n");

#	return $DCF1[$ch];
}

sub max {
	my ($a, $b) = @_;
	return ($a > $b) ? $a : $b;
}

#main

{
	my $infile = shift;
	my $outfile = shift;

	my $fhIn, my $fhOut;
	open($fhIn, "$infile") or die "cannot open $infile!\n";
	open($fhOut, "> $outfile") or die "cannot open $outfile!\n";
	binmode $fhIn;
	binmode $fhOut;

	my %infoHash;
	my @preChunkBuf, my @postChunkBuf;
	my $dataSize = wav_util::ReadWavHeader($fhIn, \%infoHash, \@preChunkBuf, \@postChunkBuf);
	wav_util::WriteWavHeader($fhOut, \@preChunkBuf);

	my $remain = $dataSize;
	while($remain > 0) {
		my @dataArray = wav_util::ReadWavData($fhIn, \%infoHash);

		for (my $i = 0; $i <= $#dataArray; $i++) {
			$dataArray[$i] = Process($dataArray[$i], $i);
		}

		wav_util::WriteWavData($fhOut, \%infoHash, @dataArray);

		$remain -= $infoHash{ "BLOCK_SIZE" };
	}

	wav_util::WriteWavTrailer($fhOut, \@postChunkBuf);

	close ($fhIn);
	close ($fhOut);

	wav_util::MaintainWavHeader($outfile, \%infoHash, $dataSize);
}

