#! /usr/bin/perl

use strict;
use FindBin;
use POSIX;

require $FindBin::RealBin . "/Dump.pm";



my $p = HTML::Dump->new();
#$p->handler(start =>  "text", "self, dtext, is_cdata");
$p->unbroken_text('TRUE'); 
$p->parse_file(shift);
